apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ecomWebsite
  annotations:
    github.com/project-slug: Devop-code/ecomWebsite
  links:
    - url: https://ecom-website-beta-ten.vercel.app/
      title: My Dashboard
      icon: dashboard
spec:
  type: other
  lifecycle: unknown
  owner: Devop-code

