apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: artist-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  definition: |
    $json: 'https://gist.githubusercontent.com/Devop-code/68f191aaa44571151f38152d2db4af09/raw/7d0b7711f8c36cfd2c09eb6d4ccde3d7e3a408a9/test-swag.json'
