apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: artist-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  definition:
    $text: 'https://gist.githubusercontent.com/Devop-code/075db0f8288a52ab1fdc1f93f6e540ef/raw/e84ab046a21c4eed6343985fb7113b657d884e40/test-swag.json'
